// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLHjGDllVNqGsaeV2arr7TkiTW6mKrjCc',
    appId: '1:819901143033:web:fca2e9bd0d3ee07380cf28',
    messagingSenderId: '819901143033',
    projectId: 'livraria-e1c4b',
    authDomain: 'livraria-e1c4b.firebaseapp.com',
    storageBucket: 'livraria-e1c4b.appspot.com',
    measurementId: 'G-HMWQ3KMMP7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1V5qwLVaQnniTsboNxJ5vqoS6mZN03Qk',
    appId: '1:819901143033:android:e9f66d8cd07b1e0a80cf28',
    messagingSenderId: '819901143033',
    projectId: 'livraria-e1c4b',
    storageBucket: 'livraria-e1c4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuxZwRXs6oDXQVJfQvIHh0s6n4j8vJh-o',
    appId: '1:819901143033:ios:cafa0d326caed5bd80cf28',
    messagingSenderId: '819901143033',
    projectId: 'livraria-e1c4b',
    storageBucket: 'livraria-e1c4b.appspot.com',
    iosBundleId: 'br.com.receitasvovo.livrariaDaDomitilda',
  );
}
